### ISSUE TITLE
ABL help

### ISSUE THREAD

**Issue by RedYu** [dominig/mkefi-agl.sh#8]
Hello, I need help with ABL for Intel platform

**Comment by dominig** [comment]
Sorry but GitHub issue is there to report BUGS.
For help please send a mail on the agl dev mailing list
   https://lists.automotivelinux.org/g/agl-dev-community
I can only advise you to provide more detail in your issue description as well as what you have already done, in order to have a chance to motivate the community to provide the required help. As you will learn in Open Source support is only provided to active people (but it's free and generally very good).
